---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootpeoject
  labels:
    app: springbootpeoject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootpeoject
  template:
    metadata:
      labels:
        app: springbootpeoject
    spec:
      containers:
        - name: springbootpeoject
          image: docker.io/phengbunath/springbootpeoject:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
